"""add order payment method

Revision ID: 8e75ad7a3a5e
Revises: b7db1abaa141
Create Date: 2026-07-11 08:41:32.936474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e75ad7a3a5e'
down_revision: Union[str, None] = 'b7db1abaa141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(length=30), nullable=True))
    op.alter_column('products', 'product_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('idx_subscription_payments_approved_by_user_id', table_name='subscription_payments')
    op.drop_index('idx_subscription_payments_store_id', table_name='subscription_payments')
    op.drop_index('idx_subscription_plans_name', table_name='subscription_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_subscription_plans_name', 'subscription_plans', ['name'], unique=False)
    op.create_index('idx_subscription_payments_store_id', 'subscription_payments', ['store_id'], unique=False)
    op.create_index('idx_subscription_payments_approved_by_user_id', 'subscription_payments', ['approved_by_user_id'], unique=False)
    op.alter_column('products', 'product_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
